name: kidsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/glitters.jpeg
