name: kidsapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.0.12
  http: ^0.13.3
  cached_network_image: ^3.3.0
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/KidsApp_logo.png
    - lib/images/avatar.jpg
